(html
 (head
  (meta[:charset UTF-8])
  (link[:rel icon :type image/png :href "/tmp/favicon.png"])
  (title ,(format-time-string "Test @%F %I:%M:%S%p")))
 (body
  (h1 "Heading 1")
  (h2 "Heading 2")
  (img[ :src ,(concat "file://" (expand-file-name "~/Pictures/test.png"))
        :alt "This is alt text."
        :width 400 :height 100])
  (a[:href "https://www.google.com"] "A link")
  (p.class "This is a " (b "classy") " paragraph.")
  (main (pre ,@(mel-read "/tmp/another.mel")))
  (p\#id.test.one.two "And this has an ID and class.")))
